---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-always-scaled
  namespace: tenant-1
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target-burst-capacity: "0"
    spec:
      containers:
        - image: kennethreitz/httpbin
          env:
            - name: TARGET
              value: httpbin
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-activator-in-path
  namespace: tenant-1
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target-burst-capacity: "-1"
    spec:
      containers:
        - image: kennethreitz/httpbin
          env:
            - name: TARGET
              value: httpbin
          ports:
            - containerPort: 80
              protocol: TCP