apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  profiles:
    - default
  security:
    dataPlane:
      mtls: true
    techPreview:
      meshConfig:
        defaultConfig:
          terminationDrainDuration: 35s
    proxy:
      networking:
        trafficControl:
          inbound:
            excludedPorts:
              - 8444 # metrics
              - 8022 # serving: wait-for-drain k8s pre-stop hook
